/**
 * The games, for learners who cannot read a lesson yet.
 *
 * Six of them, all DOM and SVG. No canvas engine, no WASM, no sprite sheet:
 * the whole set adds a few kilobytes, loads instantly on a cheap phone, and
 * works on a bad connection. That is not a compromise, it is the requirement.
 * A Godot or Unity build is five to thirty megabytes, which on a Ghanaian 3G
 * connection is minutes of waiting and real money in data, to tap three
 * mangoes. Phaser belongs later, where a topic genuinely needs physics.
 *
 * ── How they are built ──────────────────────────────────────────────────────
 *
 * Every game is the same shape: a question generated from the learner's year
 * and how they have been doing, a tap, an answer, and an immediate response.
 * One instruction at a time, no reading required, tap targets sized for a
 * four year old's finger rather than a mouse.
 *
 * Nothing is generated by a model. The AI chooses which game and how hard;
 * the game itself is written out, so it cannot produce anything unsuitable,
 * which for this age group matters more than any other property.
 *
 * Every round records an `Attempt` against the topic, exactly as a written
 * question does, so the same mastery model and the same adaptation follow a
 * four year old tapping mangoes as follow a sixth former solving equations.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import '../styles/games.css'
import {
  THINGS, gameById, nearMisses, pick, rangeFor,
  type GameId,
} from '../lib/education/games'
import {
  canSpeak, say, setVoiceOn, stop, voiceOn, whenVoicesReady,
} from '../lib/education/speak'
import type { Attempt } from '../lib/education/mastery'
import type { Stage } from '../lib/education/learner'

/** How many rounds before handing back. Short: attention, not stamina. */
const ROUNDS = 5

interface Round {
  /** What the adult reads out, or the child hears. */
  ask: string
  /** The answer, as a string, so every game reports the same way. */
  answer: string
  /** Rendered by the game itself. */
  kind: GameId
  /** Whatever that game needs. */
  data: Record<string, unknown>
}

/* ── making rounds ────────────────────────────────────────────────────────── */

const LETTERS: Array<{ letter: string, emoji: string, word: string }> = [
  { letter: 'm', emoji: '🥭', word: 'mango' },
  { letter: 'b', emoji: '🍌', word: 'banana' },
  { letter: 'f', emoji: '🐟', word: 'fish' },
  { letter: 'e', emoji: '🥚', word: 'egg' },
  { letter: 'c', emoji: '🌽', word: 'corn' },
  { letter: 't', emoji: '🍅', word: 'tomato' },
  { letter: 'd', emoji: '🥁', word: 'drum' },
  { letter: 's', emoji: '☀️', word: 'sun' },
  { letter: 'g', emoji: '🐐', word: 'goat' },
  { letter: 'h', emoji: '🏠', word: 'house' },
]

const SHAPES = ['circle', 'square', 'triangle'] as const
type ShapeName = typeof SHAPES[number]

function makeRound(kind: GameId, max: number, last?: string): Round {
  const thing = THINGS[Math.floor(Math.random() * THINGS.length)]

  switch (kind) {
    case 'count-tap': {
      /* Asked for fewer than are on screen, so the child must stop counting at
         the right place rather than tapping everything. At least two, because
         "tap 1 egg" is not counting, it is pointing. */
      const shown = Math.min(Math.max(max, 5), Math.max(5, pick(max) + 3))
      const want = Math.max(2, Math.min(shown - 1, pick(Math.min(shown, max))))
      return {
        kind,
        ask: `Tap ${want} ${want === 1 ? thing.one : thing.many}.`,
        answer: String(want),
        data: { shown, want, emoji: thing.emoji },
      }
    }
    case 'how-many': {
      const n = pick(max, last ? Number(last) : undefined)
      return {
        kind,
        ask: `How many ${thing.many}?`,
        answer: String(n),
        data: {
          n,
          emoji: thing.emoji,
          options: [n, ...nearMisses(n, 2, max)].sort(() => Math.random() - 0.5),
        },
      }
    }
    case 'more-or-fewer': {
      const a = pick(max)
      let b = pick(max)
      /* Equal groups make the question unanswerable, and one apart is the
         comparison worth practising. */
      while (b === a) b = pick(max)
      return {
        kind,
        ask: 'Tap the group with more.',
        answer: a > b ? 'left' : 'right',
        data: { a, b, emoji: thing.emoji },
      }
    }
    case 'missing-number': {
      const step = max > 20 ? (Math.random() < 0.5 ? 1 : 2) : 1
      const from = pick(Math.max(2, max - step * 4))
      const run = [0, 1, 2, 3].map(i => from + i * step)
      const gap = 1 + Math.floor(Math.random() * 2)
      const answer = run[gap]
      return {
        kind,
        ask: 'Which number is missing?',
        answer: String(answer),
        data: {
          run,
          gap,
          options: [answer, ...nearMisses(answer, 2, max)].sort(() => Math.random() - 0.5),
        },
      }
    }
    case 'first-sound': {
      const it = LETTERS[Math.floor(Math.random() * LETTERS.length)]
      const others = LETTERS.filter(l => l.letter !== it.letter)
        .sort(() => Math.random() - 0.5)
        .slice(0, 2)
      return {
        kind,
        ask: `What sound does ${it.word} start with?`,
        answer: it.letter,
        data: {
          emoji: it.emoji,
          options: [it.letter, ...others.map(o => o.letter)].sort(() => Math.random() - 0.5),
        },
      }
    }
    case 'match-shape': {
      const want = SHAPES[Math.floor(Math.random() * SHAPES.length)]
      return {
        kind,
        ask: 'Tap the shape that matches.',
        answer: want,
        data: { want, options: [...SHAPES].sort(() => Math.random() - 0.5) },
      }
    }
  }
}

/* ── the shapes, drawn rather than fetched ────────────────────────────────── */

function Shape({ name, size = 92 }: { name: ShapeName, size?: number }) {
  const half = size / 2
  return (
    <svg width={size} height={size} viewBox="0 0 100 100" aria-label={name}>
      {name === 'circle' && <circle cx="50" cy="50" r="42" fill="currentColor" />}
      {name === 'square' && <rect x="10" y="10" width="80" height="80" rx="6" fill="currentColor" />}
      {name === 'triangle' && <polygon points="50,10 92,88 8,88" fill="currentColor" />}
      <desc>{`a ${name}, ${half} across`}</desc>
    </svg>
  )
}

/* ── one round on screen ─────────────────────────────────────────────────── */

function Board({ round, verdict, onAnswer }: {
  round: Round
  verdict: null | boolean
  onAnswer: (given: string) => void
}) {
  /* For count-tap the child taps objects, so the tapped set is local state. */
  const [tapped, setTapped] = useState<number[]>([])
  const locked = verdict !== null

  const shown = Number(round.data.shown ?? 0)
  const emoji = String(round.data.emoji ?? '⭐')

  if (round.kind === 'count-tap') {
    return (
      <>
        <div className="gm-scatter">
          {Array.from({ length: shown }, (_, i) => (
            <button
              key={i}
              className={`gm-thing${tapped.includes(i) ? ' is-on' : ''}`}
              disabled={locked}
              aria-pressed={tapped.includes(i)}
              onClick={() => setTapped(t =>
                t.includes(i) ? t.filter(x => x !== i) : [...t, i])}>
              <span aria-hidden>{emoji}</span>
            </button>
          ))}
        </div>
        <div className="gm-counted">
          {tapped.length > 0 && <span className="gm-counted-n">{tapped.length}</span>}
          <button
            className="gm-go"
            disabled={locked || tapped.length === 0}
            onClick={() => onAnswer(String(tapped.length))}>
            Done
          </button>
        </div>
      </>
    )
  }

  if (round.kind === 'how-many') {
    const options = round.data.options as number[]
    return (
      <>
        <div className="gm-scatter is-still">
          {Array.from({ length: Number(round.data.n) }, (_, i) => (
            <span key={i} className="gm-thing is-still" aria-hidden>{emoji}</span>
          ))}
        </div>
        <div className="gm-choices">
          {options.map(o => (
            <button key={o} className="gm-choice is-number" disabled={locked}
              onClick={() => onAnswer(String(o))}>{o}</button>
          ))}
        </div>
      </>
    )
  }

  if (round.kind === 'more-or-fewer') {
    const a = Number(round.data.a)
    const b = Number(round.data.b)
    return (
      <div className="gm-pair">
        {(['left', 'right'] as const).map(side => (
          <button key={side} className="gm-group" disabled={locked}
            onClick={() => onAnswer(side)}>
            {Array.from({ length: side === 'left' ? a : b }, (_, i) => (
              <span key={i} aria-hidden>{emoji}</span>
            ))}
          </button>
        ))}
      </div>
    )
  }

  if (round.kind === 'missing-number') {
    const run = round.data.run as number[]
    const gap = Number(round.data.gap)
    const options = round.data.options as number[]
    return (
      <>
        <div className="gm-run">
          {run.map((n, i) => (
            <span key={i} className={`gm-run-n${i === gap ? ' is-gap' : ''}`}>
              {i === gap ? '?' : n}
            </span>
          ))}
        </div>
        <div className="gm-choices">
          {options.map(o => (
            <button key={o} className="gm-choice is-number" disabled={locked}
              onClick={() => onAnswer(String(o))}>{o}</button>
          ))}
        </div>
      </>
    )
  }

  if (round.kind === 'first-sound') {
    const options = round.data.options as string[]
    return (
      <>
        <div className="gm-big" aria-hidden>{emoji}</div>
        <div className="gm-choices">
          {options.map(o => (
            <button key={o} className="gm-choice is-letter" disabled={locked}
              onClick={() => onAnswer(o)}>{o}</button>
          ))}
        </div>
      </>
    )
  }

  const want = round.data.want as ShapeName
  const options = round.data.options as ShapeName[]
  return (
    <>
      <div className="gm-target"><Shape name={want} size={110} /></div>
      <div className="gm-choices">
        {options.map(o => (
          <button key={o} className="gm-choice is-shape" disabled={locked}
            onClick={() => onAnswer(o)}>
            <Shape name={o} />
          </button>
        ))}
      </div>
    </>
  )
}

/* ── the host ─────────────────────────────────────────────────────────────── */

export default function Games({
  gameId, topicId, topicTitle, stage, year, accuracy, onAttempt, onDone, onRead,
}: {
  gameId: GameId
  topicId: string
  topicTitle: string
  stage: Stage
  year: string
  /** How they have been doing, so the numbers are set to suit. */
  accuracy: number | null
  onAttempt: (a: Attempt) => void
  onDone: () => void
  /** Back to the written lesson, which at this age is for the adult. */
  onRead: () => void
}) {
  const game = gameById(gameId)
  const max = useMemo(() => rangeFor(stage, year, accuracy), [stage, year, accuracy])

  const [round, setRound] = useState<Round>(() => makeRound(gameId, max))
  const [verdict, setVerdict] = useState<null | boolean>(null)
  const [marks, setMarks] = useState<boolean[]>([])
  const [n, setN] = useState(0)
  const [voice, setVoice] = useState(() => canSpeak() && voiceOn())

  /**
   * Read the instruction out.
   *
   * This is what lets a child who cannot read use the platform without an
   * adult beside them. The text stays on screen either way, so a device with
   * no voice loses nothing it had before.
   *
   * Waits for the voice list on the first line only: Chrome populates it
   * asynchronously, so the very first thing said would otherwise come out in
   * the wrong voice or not at all.
   */
  const first = useRef(true)
  useEffect(() => {
    if (!voice) return
    if (first.current) {
      first.current = false
      whenVoicesReady(() => say(round.ask))
      return
    }
    say(round.ask)
    /* Only when the question changes. Re-speaking on every render would talk
       over itself every time a child taps. */
  }, [round.ask, voice])

  /* Nothing should still be talking after the game closes. */
  useEffect(() => () => stop(), [])

  const answer = useCallback((given: string) => {
    if (verdict !== null) return
    const right = given === round.answer
    setVerdict(right)
    setMarks(m => [...m, right])
    /* Said as well as shown, and the right answer named aloud when they miss,
       because a child who cannot read cannot be told in writing. */
    if (voice) {
      say(right ? 'Yes. Well done.' : `Not that one. It was ${round.answer}.`)
    }
    onAttempt({
      objectiveId: topicId,
      isCorrect: right,
      hintUsed: false,
      at: new Date().toISOString(),
    })
  }, [verdict, round.answer, onAttempt, topicId, voice])

  const next = () => {
    if (n + 1 >= ROUNDS) { onDone(); return }
    setN(i => i + 1)
    setVerdict(null)
    setRound(makeRound(gameId, max, round.answer))
  }

  const score = marks.filter(Boolean).length

  return (
    <div className="gm">
      <div className="gm-top">
        <span className="gm-dots" aria-label={`round ${n + 1} of ${ROUNDS}`}>
          {Array.from({ length: ROUNDS }, (_, i) => (
            <i key={i} className={
              i < marks.length ? (marks[i] ? 'is-right' : 'is-wrong') : i === n ? 'is-now' : ''
            } />
          ))}
        </span>
        <span className="gm-controls">
          {canSpeak() && (
            <>
              {/* Repeat, because a child will want the instruction again and
                  should not have to wait for an adult to read it. */}
              <button
                className="gm-icon"
                aria-label="Say it again"
                title="Say it again"
                onClick={() => { setVoice(true); setVoiceOn(true); say(round.ask) }}>
                🔊
              </button>
              {/* Off, because thirty phones talking at once in a classroom is
                  the reason this switch is here and not buried in a setting. */}
              <button
                className={`gm-icon${voice ? ' is-on' : ''}`}
                aria-label={voice ? 'Turn the voice off' : 'Turn the voice on'}
                aria-pressed={voice}
                title={voice ? 'Voice on' : 'Voice off'}
                onClick={() => {
                  const next = !voice
                  setVoice(next)
                  setVoiceOn(next)
                  if (next) say(round.ask)
                }}>
                {voice ? '🔔' : '🔕'}
              </button>
            </>
          )}
          <button className="gm-quiet" onClick={onRead}>For the grown up</button>
        </span>
      </div>

      {/* Read aloud by whoever is sitting with them. Large, because at this age
          an adult is often holding the phone at arm's length. */}
      <p className="gm-ask">{round.ask}</p>

      <Board key={`${n}`} round={round} verdict={verdict} onAnswer={answer} />

      {verdict !== null && (
        <div className={`gm-said${verdict ? ' is-right' : ' is-wrong'}`}>
          <span className="gm-said-mark" aria-hidden>{verdict ? '✓' : '✗'}</span>
          <span>
            {verdict
              ? 'Yes. Well done.'
              /* The right answer, shown rather than described, because a child
                 who cannot read cannot be told. */
              : `Not that one. It was ${round.answer}.`}
          </span>
          <button className="gm-go" onClick={next}>
            {n + 1 >= ROUNDS ? 'Finish' : 'Next'}
          </button>
        </div>
      )}

      <p className="gm-foot">
        {game?.name ?? 'Game'} · {topicTitle} · {score} of {marks.length} right
      </p>
    </div>
  )
}
